### ISSUE TITLE
Getting all parameters in a URI template

### ISSUE THREAD

**Issue by marcelotto** [sirikid/yuri_template#1]
Would it be possible to add a function that returns all parameters in a URI template (or is there something like that already that I simply couldn't find) or would you be willing to accept a PR for that?

Example:

```elixir
iex> template = YuriTemplate.parse("http://example.com/people/{first_name}-{last_name}")
iex> YuriTemplate.parameters(template)
[:first_name, :last_name]
```

**Comment by sirikid** [comment]
> Would it be possible to add a function that returns all parameters in a URI template (or is there something like that already that I simply couldn't find) or would you be willing to accept a PR for that?

Yes, I just recently thought about it.

**Comment by marcelotto** [comment]
Awesome. Thanks a lot. ❤️
